package io.jromanmartin.utils;

import io.jromanmartin.model.SourceObject;
import io.smallrye.mutiny.Multi;
import org.eclipse.microprofile.reactive.messaging.Outgoing;

import javax.enterprise.context.ApplicationScoped;
import java.time.Duration;
import java.util.Random;

/**
 * A bean producing random tokens every 5 seconds.
 * The tokens are written to a Kafka topic (hackathon-topic).
 * The Kafka configuration is specified in the application configuration.
 */
@ApplicationScoped
public class TokenGenerator {

    private Random random = new Random();

    @Outgoing("generated-token")
    public Multi<SourceObject> generate() {
        return Multi.createFrom().ticks().every(Duration.ofMillis(5000))
                .onOverflow().drop()
                .map(tick -> new SourceObject("token-" + random.nextInt(100000), "autogenerated"));
    }

}
